theme: jekyll-theme-minimal
title: Steven (Siwei) Ye
description: <a href="mailto:stevenysw@g.ucla.edu"><img src="/style_files/gmail.png" width="10" height="10"></a> <a href="https://github.com/stevenysw/"><img src="http://i.imgur.com/0o48UoR.png" width="10" height="10"></a> <a href="https://www.facebook.com/steven2249/"><img src="http://i.imgur.com/P3YfQoD.png" width="10" height="10"></a> 
