theme: jekyll-theme-minimal
title: Steven (Siwei) Ye
description: <a href="https://github.com/stevenysw/"><img src="http://i.imgur.com/0o48UoR.png"></a> <a href="https://www.facebook.com/steven2249/"><img src="http://i.imgur.com/P3YfQoD.png"></a> 
