theme: jekyll-theme-minimal
title: Steven (Siwei) Ye
description: Ph.D. Student in Statistics at UCLA
[![alt text][1.1]][1]
[![alt text][2.1]][2]

[1.1]: http://i.imgur.com/P3YfQoD.png
[2.1]: http://i.imgur.com/0o48UoR.png 

[1]: https://www.facebook.com/steven2249/
[2]: https://github.com/stevenysw/

