theme: jekyll-theme-minimal
title: Steven (Siwei) Ye
description: Ph.D. Student in Statistics at UCLA
social-network-links:
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: c/daattali

