theme: jekyll-theme-minimal
title: Steven (Siwei) Ye
description: <a href="mailto:stevenysw@g.ucla.edu"><img src="/style_files/gmail.png" width="15" height="15"></a> <a href="https://github.com/stevenysw/"><img src="/style_files/Github.png" width="15" height="15"></a>
<a href="https://www.linkedin.com/in/stevenysw/"><img src="/style_files/LinkedIn.png" width="15" height="15"></a> 
<a href="https://www.facebook.com/steven2249/"><img src="http://i.imgur.com/P3YfQoD.png" width="15" height="15"></a> 
